export const MapBoxStyles = [
  {name: 'MapBox Streets', value: 'mapbox/streets-v11'},
  {name: 'MapBox Outdoors', value: 'mapbox/outdoors-v11'},
  {name: 'MapBox Light', value: 'mapbox/light-v10'},
  {name: 'MapBox Dark', value: 'mapbox/dark-v10'},
  {name: 'MapBox Satellite', value: 'mapbox/satellite-v9'},
  {name: 'MapBox Satellite Streets', value: 'mapbox/satellite-streets,-v11'},
  {name: 'MapBox Navigation Day', value: 'mapbox/navigation-day-v1'},
  {name: 'MapBox Navigation Night', value: 'mapbox/navigation-night-v1'},
];
export const MapBoxTilesets = [
  {name: 'MapBox Streets', value: 'mapbox.mapbox-streets-v8'},
  {name: 'MapBox Terrain', value: 'mapbox.mapbox-terrain-v2'},
];
export const directionsExclude = [
  'motorway',
  'toll',
  'ferry',
  'unpaved',
  'cash_only_tolls',
];
export const makiIcons = [
  'aerialway',
  'airfield',
  'airport',
  'alcohol-shop',
  'american-football',
  'amusement-park',
  'animal-shelter',
  'aquarium',
  'arrow',
  'art-gallery',
  'attraction',
  'bakery',
  'bank-JP',
  'bank',
  'bar',
  'barrier',
  'baseball',
  'basketball',
  'bbq',
  'beach',
  'beer',
  'bicycle-share',
  'bicycle',
  'blood-bank',
  'bowling-alley',
  'bridge',
  'building-alt1',
  'building',
  'bus',
  'cafe',
  'campsite',
  'car-rental',
  'car-repair',
  'car',
  'casino',
  'castle-JP',
  'castle',
  'caution',
  'cemetery-JP',
  'cemetery',
  'charging-station',
  'cinema',
  'circle-stroked',
  'circle',
  'city',
  'clothing-store',
  'college-JP',
  'college',
  'commercial',
  'communications-tower',
  'confectionery',
  'construction',
  'convenience',
  'cricket',
  'cross',
  'dam',
  'danger',
  'defibrillator',
  'dentist',
  'diamond',
  'doctor',
  'dog-park',
  'drinking-water',
  'elevator',
  'embassy',
  'emergency-phone',
  'entrance-alt1',
  'entrance',
  'farm',
  'fast-food',
  'fence',
  'ferry-JP',
  'ferry',
  'fire-station-JP',
  'fire-station',
  'fitness-centre',
  'florist',
  'fuel',
  'furniture',
  'gaming',
  'garden-centre',
  'garden',
  'gate',
  'gift',
  'globe',
  'golf',
  'grocery',
  'hairdresser',
  'harbor',
  'hardware',
  'heart',
  'heliport',
  'highway-rest-area',
  'historic',
  'home',
  'horse-riding',
  'hospital-JP',
  'hospital',
  'hot-spring',
  'ice-cream',
  'industry',
  'information',
  'jewelry-store',
  'karaoke',
  'landmark-JP',
  'landmark',
  'landuse',
  'laundry',
  'library',
  'lift-gate',
  'lighthouse-JP',
  'lighthouse',
  'lodging',
  'logging',
  'marker-stroked',
  'marker',
  'mobile-phone',
  'monument-JP',
  'monument',
  'mountain',
  'museum',
  'music',
  'natural',
  'observation-tower',
  'optician',
  'paint',
  'park-alt1',
  'park',
  'parking-garage',
  'parking-paid',
  'parking',
  'pharmacy',
  'picnic-site',
  'pitch',
  'place-of-worship',
  'playground',
  'police-JP',
  'police',
  'post-JP',
  'post',
  'prison',
  'racetrack-boat',
  'racetrack-cycling',
  'racetrack-horse',
  'racetrack',
  'rail-light',
  'rail-metro',
  'rail',
  'ranger-station',
  'recycling',
  'religious-buddhist',
  'religious-christian',
  'religious-jewish',
  'religious-muslim',
  'religious-shinto',
  'residential-community',
  'restaurant-bbq',
  'restaurant-noodle',
  'restaurant-pizza',
  'restaurant-seafood',
  'restaurant-sushi',
  'restaurant',
  'road-accident',
  'roadblock',
  'rocket',
  'school-JP',
  'school',
  'scooter',
  'shelter',
  'shoe',
  'shop',
  'skateboard',
  'skiing',
  'slaughterhouse',
  'slipway',
  'snowmobile',
  'soccer',
  'square-stroked',
  'square',
  'stadium',
  'star-stroked',
  'star',
  'suitcase',
  'swimming',
  'table-tennis',
  'teahouse',
  'telephone',
  'tennis',
  'theatre',
  'toilet',
  'toll-booth',
  'town-hall',
  'town',
  'triangle-stroked',
  'triangle',
  'tunnel',
  'veterinary',
  'viewpoint',
  'village',
  'volcano',
  'volleyball',
  'warehouse',
  'waste-basket',
  'watch',
  'water',
  'waterfall',
  'watermill',
  'wetland',
  'wheelchair',
  'windmill',
  'zoo',
];
export const CountryCodes: {[key: string]: string} = {
  AF: 'Afghanistan',
  AX: 'Aland Islands',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua And Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia',
  BA: 'Bosnia And Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  CV: 'Cape Verde',
  KY: 'Cayman Islands',
  CF: 'Central African Republic',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands',
  CO: 'Colombia',
  KM: 'Comoros',
  CG: 'Congo',
  CD: 'Congo, Democratic Republic',
  CK: 'Cook Islands',
  CR: 'Costa Rica',
  CI: 'Cote D"Ivoire',
  HR: 'Croatia',
  CU: 'Cuba',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (Malvinas)',
  FO: 'Faroe Islands',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories',
  GA: 'Gabon',
  GM: 'Gambia',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island & Mcdonald Islands',
  VA: 'Holy See (Vatican City State)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran, Islamic Republic Of',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle Of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KR: 'Korea',
  KP: 'North Korea',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Lao People"s Democratic Republic',
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libyan Arab Jamahiriya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MK: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia, Federated States Of',
  MD: 'Moldova',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestinian Territory, Occupied',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RE: 'Reunion',
  RO: 'Romania',
  RU: 'Russian Federation',
  RW: 'Rwanda',
  BL: 'Saint Barthelemy',
  SH: 'Saint Helena',
  KN: 'Saint Kitts And Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  PM: 'Saint Pierre And Miquelon',
  VC: 'Saint Vincent And Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome And Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia And Sandwich Isl.',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan',
  SR: 'Suriname',
  SJ: 'Svalbard And Jan Mayen',
  SZ: 'Swaziland',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad And Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks And Caicos Islands',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States',
  UM: 'United States Outlying Islands',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela',
  VN: 'Vietnam',
  VG: 'Virgin Islands, British',
  VI: 'Virgin Islands, U.S.',
  WF: 'Wallis And Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
};

export const MapboxPlaceTypes = [
  'country',
  'region',
  'postcode',
  'district',
  'place',
  'locality',
  'neighborhood',
  'address',
  'poi',
];
